## Datasets

In [1]:
import pandas as pd 
import numpy as np
import configparser
config = configparser.ConfigParser()

In [2]:
a=open('folder_containing datasets','r')

d=a.readlines()
l=[]
for i in d:
    # use rstrip to remove extension(eg: .csv,.ini,etc)
    i=i.rstrip()
    i=i[:-5]
    
    l.append(i)
#modyifying lisy l because breast-cancer-wisconsin-original is named incorrectly in data_selections

In [4]:
#extract all file names from folder data
import glob
files = glob.glob('data/*.*')

#create DataFrame by sorted filenames

df = pd.DataFrame(sorted(files), columns=['data'])

#create column for categories

df['g'] = df['data'].str.split('\\').str[1]
#filter only that files end with values in list

include = ['.data.orig','data.orig.custom']

pat = '|'.join([x + '$' for x in include])

df = df[df['data'].str.contains(pat)]
#files are sorted, so data.orig.custom are always last for each group

#dropping duplicates get data.orig.custom if exist else .data.orig

df = df.drop_duplicates('g', keep='last')
 
#create dictionary by groups and filenames

d = df.set_index('g')['data'].to_dict()
#in loop create dictionary of DataFrames

#separator is same, so not parsed

dfs = {}

for k,v in d.items():

    config.read('data\\' + k + '\\config.ini')

    s = config['info']['header_lines']
    sep= config['info']['separator']
    c=config['info']['value_indices']
        
    if (sep==''):
        sep1='\t'
    elif (sep=='comma'):
        sep1=','
    elif (sep==';'):
        sep1=';'    
    dfs[k] = pd.read_csv(v,delimiter=sep1, header=None, skiprows=int(s),error_bad_lines=False)
    if (len(dfs[k].columns)==1):
        dfs[k] = pd.read_csv(v,delimiter=" ", header=None, skiprows=int(s),error_bad_lines=False)
    
    print(dfs[k].info(),"\n",a)

#print(dfs['acute-inflammations-1'])

#df.describe

#df.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
0    4177 non-null object
1    4177 non-null float64
2    4177 non-null float64
3    4177 non-null float64
4    4177 non-null float64
5    4177 non-null float64
6    4177 non-null float64
7    4177 non-null float64
8    4177 non-null int64
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
0    120 non-null float64
1    120 non-null object
2    120 non-null object
3    120 non-null object
4    120 non-null object
5    120 non-null object
6    120 non-null object
7    120 non-null object
dtypes: float64(1), object(7)
memory usage: 7.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
0    120 non-null float64
1    120 non-null object
2    120 non-null object
3    120 non-null object
4    120 non-null object
5    120 non-null object
6    120 non-null object
7    120 non-null object
dtypes: float64(1), object(7)
memory usage: 7.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Columns: 280 entries, 0 to 279
dtypes: float64(120), int64(155), object(5)
memory usage: 988.8+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 5 columns):
0    625 non-null object
1    625 non-null int64
2    625 non-null int64
3    625 non-null int64
4    625 non-null int64
dtypes: int64(4), object(1)
memory usage: 24.5+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
0    20 non-null object
1    20 non-null object
2    20 non-null object
3    20 non-null object
4    20 non-null object
dtypes: object(5)
memory usage: 880.0+ bytes
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
0    20 non-null object
1    20 non-null object
2    20 non-null object
3    20 non-null object
4    20 non-null object
dtypes: object(5)
memory usage: 880.0+ bytes
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
0    20 non-null object
1    20 non-null object
2    20 non-null object
3    20 non-null object
4    20 non-null object
dtypes: object(5)
memory usage: 880.0+ bytes
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
0    16 non-null object
1    16 non-null object
2    16 non-null object
3    16 non-null object
4    16 non-null object
dtypes: object(5)
memory usage: 720.0+ bytes
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
0    1372 non-null float64
1    1372 non-null float64
2    1372 non-null float64
3    1372 non-null float64
4    1372 non-null int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
0    748 non-null int64
1    748 non-null int64
2    748 non-null int64
3    748 non-null int64
4    748 non-null int64
dtypes: int64(5)
memory usage: 29.3 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
0     569 non-null int64
1     569 non-null object
2     569 non-null float64
3     569 non-null float64
4     569 non-null float64
5     569 non-null float64
6     569 non-null float64
7     569 non-null float64
8     569 non-null float64
9     569 non-null float64
10    569 non-null float64
11    569 non-null float64
12    569 non-null float64
13    569 non-null float64
14    569 non-null float64
15    569 non-null float64
16    569 non-null float64
17    569 non-null float64
18    569 non-null float64
19    569 non-null float64
20    569 non-null float64
21    569 non-null float64
22    569 non-null float64
23    569 non-null float64
24    569 non-null float64
25    569 non-null float64
26    569 non-null float64
27    569 non-null float64
28    569 non-null float64
29    569 non-null float64
30    569 non-null float64
31    569 non-null float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
0     699 non-null int64
1     699 non-null int64
2     699 non-null int64
3     699 non-null int64
4     699 non-null int64
5     699 non-null int64
6     699 non-null object
7     699 non-null int64
8     699 non-null int64
9     699 non-null int64
10    699 non-null int64
dtypes: int64(10), object(1)
memory usage: 60.1+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 35 columns):
0     198 non-null int64
1     198 non-null object
2     198 non-null int64
3     198 non-null float64
4     198 non-null float64
5     198 non-null float64
6     198 non-null float64
7     198 non-null float64
8     198 non-null float64
9     198 non-null float64
10    198 non-null float64
11    198 non-null float64
12    198 non-null float64
13    198 non-null float64
14    198 non-null float64
15    198 non-null float64
16    198 non-null float64
17    198 non-null float64
18    198 non-null float64
19    198 non-null float64
20    198 non-null float64
21    198 non-null float64
22    198 non-null float64
23    198 non-null float64
24    198 non-null float64
25    198 non-null float64
26    198 non-null float64
27    198 non-null float64
28    198 non-null float64
29    198 non-null float64
30    198 non-null float64
31    198 non-null float64
32    198 non-null float64
33    198 non-null float64
34    198 non-null object
dtypes: float64(31), int64(2), object(2)
memory usage: 54.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
0    1728 non-null object
1    1728 non-null object
2    1728 non-null object
3    1728 non-null object
4    1728 non-null object
5    1728 non-null object
6    1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3196 entries, 0 to 3195
Data columns (total 37 columns):
0     3196 non-null object
1     3196 non-null object
2     3196 non-null object
3     3196 non-null object
4     3196 non-null object
5     3196 non-null object
6     3196 non-null object
7     3196 non-null object
8     3196 non-null object
9     3196 non-null object
10    3196 non-null object
11    3196 non-null object
12    3196 non-null object
13    3196 non-null object
14    3196 non-null object
15    3196 non-null object
16    3196 non-null object
17    3196 non-null object
18    3196 non-null object
19    3196 non-null object
20    3196 non-null object
21    3196 non-null object
22    3196 non-null object
23    3196 non-null object
24    3196 non-null object
25    3196 non-null object
26    3196 non-null object
27    3196 non-null object
28    3196 non-null object
29    3196 non-null object
30    3196 non-null object
31    3196 non-null object
32    3196 non-null object
33    3196 non-null object
34    3196 non-null object
35    3196 non-null object
36    3196 non-null object
dtypes: object(37)
memory usage: 923.9+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28056 entries, 0 to 28055
Data columns (total 7 columns):
0    28056 non-null object
1    28056 non-null int64
2    28056 non-null object
3    28056 non-null int64
4    28056 non-null object
5    28056 non-null int64
6    28056 non-null object
dtypes: int64(3), object(4)
memory usage: 1.5+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 21 columns):
0     540 non-null int64
1     540 non-null int64
2     540 non-null float64
3     540 non-null float64
4     540 non-null float64
5     540 non-null float64
6     540 non-null float64
7     540 non-null float64
8     540 non-null float64
9     540 non-null float64
10    540 non-null float64
11    540 non-null float64
12    540 non-null float64
13    540 non-null float64
14    540 non-null float64
15    540 non-null float64
16    540 non-null float64
17    540 non-null float64
18    540 non-null float64
19    540 non-null float64
20    540 non-null int64
dtypes: float64(18), int64(3)
memory usage: 88.7 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080 entries, 0 to 1079
Columns: 857 entries, 0 to 856
dtypes: int64(857)
memory usage: 7.1 MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
0     435 non-null object
1     435 non-null object
2     435 non-null object
3     435 non-null object
4     435 non-null object
5     435 non-null object
6     435 non-null object
7     435 non-null object
8     435 non-null object
9     435 non-null object
10    435 non-null object
11    435 non-null object
12    435 non-null object
13    435 non-null object
14    435 non-null object
15    435 non-null object
16    435 non-null object
dtypes: object(17)
memory usage: 57.9+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
0     208 non-null float64
1     208 non-null float64
2     208 non-null float64
3     208 non-null float64
4     208 non-null float64
5     208 non-null float64
6     208 non-null float64
7     208 non-null float64
8     208 non-null float64
9     208 non-null float64
10    208 non-null float64
11    208 non-null float64
12    208 non-null float64
13    208 non-null float64
14    208 non-null float64
15    208 non-null float64
16    208 non-null float64
17    208 non-null float64
18    208 non-null float64
19    208 non-null float64
20    208 non-null float64
21    208 non-null float64
22    208 non-null float64
23    208 non-null float64
24    208 non-null float64
25    208 non-null float64
26    208 non-null float64
27    208 non-null float64
28    208 non-null float64
29    208 non-null float64
30    208 non-null float64
31    208 non-null float64
32    208 non-null float64
33    208 non-null float64
34    208 non-null float64
35    208 non-null float64
36    208 non-null float64
37    208 non-null float64
38    208 non-null float64
39    208 non-null float64
40    208 non-null float64
41    208 non-null float64
42    208 non-null float64
43    208 non-null float64
44    208 non-null float64
45    208 non-null float64
46    208 non-null float64
47    208 non-null float64
48    208 non-null float64
49    208 non-null float64
50    208 non-null float64
51    208 non-null float64
52    208 non-null float64
53    208 non-null float64
54    208 non-null float64
55    208 non-null float64
56    208 non-null float64
57    208 non-null float64
58    208 non-null float64
59    208 non-null float64
60    208 non-null object
dtypes: float64(60), object(1)
memory usage: 99.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 15 columns):
0     990 non-null int64
1     990 non-null int64
2     990 non-null int64
3     990 non-null float64
4     990 non-null float64
5     990 non-null float64
6     990 non-null float64
7     990 non-null float64
8     990 non-null float64
9     990 non-null float64
10    990 non-null float64
11    990 non-null float64
12    990 non-null float64
13    89 non-null float64
14    901 non-null float64
dtypes: float64(12), int64(3)
memory usage: 116.1 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1473 entries, 0 to 1472
Data columns (total 10 columns):
0    1473 non-null int64
1    1473 non-null int64
2    1473 non-null int64
3    1473 non-null int64
4    1473 non-null int64
5    1473 non-null int64
6    1473 non-null int64
7    1473 non-null int64
8    1473 non-null int64
9    1473 non-null int64
dtypes: int64(10)
memory usage: 115.2 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
0     690 non-null object
1     690 non-null object
2     690 non-null float64
3     690 non-null object
4     690 non-null object
5     690 non-null object
6     690 non-null object
7     690 non-null float64
8     690 non-null object
9     690 non-null object
10    690 non-null int64
11    690 non-null object
12    690 non-null object
13    690 non-null object
14    690 non-null int64
15    690 non-null object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 40 columns):
0     540 non-null int64
1     540 non-null object
2     540 non-null object
3     540 non-null int64
4     540 non-null object
5     540 non-null object
6     540 non-null object
7     540 non-null object
8     540 non-null object
9     540 non-null object
10    540 non-null object
11    540 non-null object
12    540 non-null object
13    540 non-null object
14    540 non-null object
15    540 non-null int64
16    540 non-null int64
17    540 non-null object
18    540 non-null object
19    540 non-null object
20    540 non-null object
21    540 non-null object
22    540 non-null object
23    540 non-null object
24    540 non-null object
25    540 non-null object
26    540 non-null object
27    540 non-null object
28    540 non-null object
29    540 non-null object
30    540 non-null object
31    540 non-null object
32    540 non-null object
33    540 non-null object
34    540 non-null object
35    540 non-null object
36    540 non-null object
37    540 non-null object
38    540 non-null object
39    540 non-null object
dtypes: int64(4), object(36)
memory usage: 168.8+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 35 columns):
0     366 non-null int64
1     366 non-null int64
2     366 non-null int64
3     366 non-null int64
4     366 non-null int64
5     366 non-null int64
6     366 non-null int64
7     366 non-null int64
8     366 non-null int64
9     366 non-null int64
10    366 non-null int64
11    366 non-null int64
12    366 non-null int64
13    366 non-null int64
14    366 non-null int64
15    366 non-null int64
16    366 non-null int64
17    366 non-null int64
18    366 non-null int64
19    366 non-null int64
20    366 non-null int64
21    366 non-null int64
22    366 non-null int64
23    366 non-null int64
24    366 non-null int64
25    366 non-null int64
26    366 non-null int64
27    366 non-null int64
28    366 non-null int64
29    366 non-null int64
30    366 non-null int64
31    366 non-null int64
32    366 non-null int64
33    366 non-null object
34    366 non-null int64
dtypes: int64(34), object(1)
memory usage: 100.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 13 columns):
0     132 non-null object
1     132 non-null object
2     132 non-null object
3     132 non-null object
4     132 non-null object
5     132 non-null object
6     132 non-null object
7     132 non-null object
8     132 non-null object
9     132 non-null object
10    132 non-null object
11    132 non-null object
12    132 non-null object
dtypes: object(13)
memory usage: 13.5+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 19 columns):
0     335 non-null object
1     0 non-null float64
2     282 non-null float64
3     53 non-null float64
4     282 non-null float64
5     53 non-null float64
6     282 non-null float64
7     53 non-null float64
8     282 non-null float64
9     53 non-null float64
10    282 non-null float64
11    53 non-null float64
12    282 non-null float64
13    53 non-null float64
14    282 non-null float64
15    53 non-null float64
16    39 non-null object
17    248 non-null object
18    48 non-null object
dtypes: float64(15), object(4)
memory usage: 49.8+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null int64
3    100 non-null int64
4    100 non-null int64
5    100 non-null int64
6    100 non-null float64
7    100 non-null int64
8    100 non-null float64
9    100 non-null object
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 30 columns):
0     194 non-null object
1     194 non-null int64
2     194 non-null int64
3     194 non-null int64
4     194 non-null int64
5     194 non-null int64
6     194 non-null int64
7     194 non-null int64
8     194 non-null int64
9     194 non-null int64
10    194 non-null int64
11    194 non-null int64
12    194 non-null int64
13    194 non-null int64
14    194 non-null int64
15    194 non-null int64
16    194 non-null int64
17    194 non-null object
18    194 non-null int64
19    194 non-null int64
20    194 non-null int64
21    194 non-null int64
22    194 non-null int64
23    194 non-null int64
24    194 non-null int64
25    194 non-null int64
26    194 non-null int64
27    194 non-null int64
28    194 non-null object
29    194 non-null object
dtypes: int64(26), object(4)
memory usage: 45.5+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 11 columns):
0     214 non-null int64
1     214 non-null float64
2     214 non-null float64
3     214 non-null float64
4     214 non-null float64
5     214 non-null float64
6     214 non-null float64
7     214 non-null float64
8     214 non-null float64
9     214 non-null float64
10    214 non-null int64
dtypes: float64(9), int64(2)
memory usage: 18.5 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 4 columns):
0    306 non-null int64
1    306 non-null int64
2    306 non-null int64
3    306 non-null int64
dtypes: int64(4)
memory usage: 9.6 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 6 columns):
0    132 non-null int64
1    132 non-null int64
2    132 non-null int64
3    132 non-null int64
4    132 non-null int64
5    132 non-null int64
dtypes: int64(6)
memory usage: 6.3 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
0     303 non-null float64
1     303 non-null float64
2     303 non-null float64
3     303 non-null float64
4     303 non-null float64
5     303 non-null float64
6     303 non-null float64
7     303 non-null float64
8     303 non-null float64
9     303 non-null float64
10    303 non-null float64
11    303 non-null object
12    303 non-null object
13    303 non-null int64
dtypes: float64(11), int64(1), object(2)
memory usage: 33.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
0     294 non-null int64
1     294 non-null int64
2     294 non-null int64
3     294 non-null object
4     294 non-null object
5     294 non-null object
6     294 non-null object
7     294 non-null object
8     294 non-null object
9     294 non-null float64
10    294 non-null object
11    294 non-null object
12    294 non-null object
13    294 non-null int64
dtypes: float64(1), int64(4), object(9)
memory usage: 32.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
0     123 non-null int64
1     123 non-null int64
2     123 non-null int64
3     123 non-null object
4     123 non-null int64
5     123 non-null object
6     123 non-null object
7     123 non-null object
8     123 non-null object
9     123 non-null object
10    123 non-null object
11    123 non-null object
12    123 non-null object
13    123 non-null int64
dtypes: int64(5), object(9)
memory usage: 13.5+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
0     200 non-null int64
1     200 non-null int64
2     200 non-null int64
3     200 non-null object
4     200 non-null object
5     200 non-null object
6     200 non-null int64
7     200 non-null object
8     200 non-null object
9     200 non-null object
10    200 non-null object
11    200 non-null object
12    200 non-null object
13    200 non-null int64
dtypes: int64(5), object(9)
memory usage: 22.0+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 20 columns):
0     155 non-null int64
1     155 non-null int64
2     155 non-null int64
3     155 non-null object
4     155 non-null int64
5     155 non-null object
6     155 non-null object
7     155 non-null object
8     155 non-null object
9     155 non-null object
10    155 non-null object
11    155 non-null object
12    155 non-null object
13    155 non-null object
14    155 non-null object
15    155 non-null object
16    155 non-null object
17    155 non-null object
18    155 non-null object
19    155 non-null int64
dtypes: int64(5), object(15)
memory usage: 24.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606 entries, 0 to 605
Columns: 101 entries, 0 to 100
dtypes: float64(100), int64(1)
memory usage: 478.2 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606 entries, 0 to 605
Columns: 101 entries, 0 to 100
dtypes: float64(100), int64(1)
memory usage: 478.2 KB

b'Skipping line 48: expected 19 fields, saw 20\n'
b'Skipping line 2: expected 28 fields, saw 29\nSkipping line 3: expected 28 fields, saw 29\nSkipping line 4: expected 28 fields, saw 29\nSkipping line 5: expected 28 fields, saw 29\nSkipping line 6: expected 28 fields, saw 29\nSkipping line 7: expected 28 fields, saw 29\nSkipping line 8: expected 28 fields, saw 29\nSkipping line 9: expected 28 fields, saw 29\nSkipping line 10: expected 28 fields, saw 29\nSkipping line 11: expected 28 fields, saw 29\nSkipping line 12: expected 28 fields, saw 29\nSkipping line 13: expected 28 fields, saw 29\nSkipping line 14: expected 28 fields, saw 29\nSkipping line 15: expected 28 fields, saw 29\nSkipping line 16: expected 28 fields, saw 29\nSkipping line 17: expected 28 fields, saw 29\nSkipping line 18: expected 28 fields, saw 29\nSkipping line 19: expected 28 fields, saw 29\nSkipping line 20: expected 28 fields, saw 29\nSkipping line 21: expected 28 fields, saw 29\nSkipping line 22: expected 28 fields, saw 29\nSkipping line 23: expected 28 fields, saw 29\nSkipping line 24: expected 28 fields, saw 29\nSkipping line 25: expected 28 fields, saw 29\nSkipping line 26: expected 28 fields, saw 29\nSkipping line 27: expected 28 fields, saw 29\nSkipping line 28: expected 28 fields, saw 29\nSkipping line 29: expected 28 fields, saw 29\nSkipping line 30: expected 28 fields, saw 29\nSkipping line 31: expected 28 fields, saw 29\nSkipping line 32: expected 28 fields, saw 29\nSkipping line 33: expected 28 fields, saw 29\nSkipping line 34: expected 28 fields, saw 29\nSkipping line 35: expected 28 fields, saw 29\nSkipping line 36: expected 28 fields, saw 29\nSkipping line 37: expected 28 fields, saw 29\nSkipping line 38: expected 28 fields, saw 29\nSkipping line 39: expected 28 fields, saw 29\nSkipping line 40: expected 28 fields, saw 29\nSkipping line 41: expected 28 fields, saw 29\nSkipping line 42: expected 28 fields, saw 29\nSkipping line 43: expected 28 fields, saw 29\nSkipping line 44: expected 28 fields, saw 29\nSkipping line 45: expected 28 fields, saw 29\nSkipping line 46: expected 28 fields, saw 29\nSkipping line 47: expected 28 fields, saw 29\nSkipping line 48: expected 28 fields, saw 29\nSkipping line 49: expected 28 fields, saw 29\nSkipping line 50: expected 28 fields, saw 29\nSkipping line 51: expected 28 fields, saw 29\nSkipping line 52: expected 28 fields, saw 29\nSkipping line 53: expected 28 fields, saw 29\nSkipping line 54: expected 28 fields, saw 29\nSkipping line 55: expected 28 fields, saw 29\nSkipping line 56: expected 28 fields, saw 29\nSkipping line 57: expected 28 fields, saw 29\nSkipping line 58: expected 28 fields, saw 29\nSkipping line 59: expected 28 fields, saw 29\nSkipping line 60: expected 28 fields, saw 29\nSkipping line 61: expected 28 fields, saw 29\nSkipping line 62: expected 28 fields, saw 29\nSkipping line 63: expected 28 fields, saw 29\nSkipping line 64: expected 28 fields, saw 29\nSkipping line 65: expected 28 fields, saw 29\nSkipping line 66: expected 28 fields, saw 29\nSkipping line 67: expected 28 fields, saw 29\nSkipping line 68: expected 28 fields, saw 29\nSkipping line 69: expected 28 fields, saw 29\nSkipping line 70: expected 28 fields, saw 29\nSkipping line 71: expected 28 fields, saw 29\nSkipping line 72: expected 28 fields, saw 29\nSkipping line 73: expected 28 fields, saw 29\nSkipping line 74: expected 28 fields, saw 29\nSkipping line 75: expected 28 fields, saw 29\nSkipping line 76: expected 28 fields, saw 29\nSkipping line 77: expected 28 fields, saw 29\nSkipping line 78: expected 28 fields, saw 29\nSkipping line 79: expected 28 fields, saw 29\nSkipping line 80: expected 28 fields, saw 29\nSkipping line 81: expected 28 fields, saw 29\nSkipping line 82: expected 28 fields, saw 29\nSkipping line 83: expected 28 fields, saw 29\nSkipping line 84: expected 28 fields, saw 29\nSkipping line 85: expected 28 fields, saw 29\nSkipping line 86: expected 28 fields, saw 29\nSkipping line 87: expected 28 fields, saw 29\nSkipping line 88: expected 28 fields, saw 29\nSkipping line 89: expected 28 fields, saw 29\nSkipping line 90: expected 28 fields, saw 29\nSkipping line 91: expected 28 fields, saw 29\nSkipping line 92: expected 28 fields, saw 29\nSkipping line 93: expected 28 fields, saw 29\nSkipping line 94: expected 28 fields, saw 29\nSkipping line 95: expected 28 fields, saw 29\nSkipping line 96: expected 28 fields, saw 29\nSkipping line 97: expected 28 fields, saw 29\nSkipping line 98: expected 28 fields, saw 29\nSkipping line 99: expected 28 fields, saw 29\nSkipping line 100: expected 28 fields, saw 29\nSkipping line 101: expected 28 fields, saw 29\nSkipping line 102: expected 28 fields, saw 29\nSkipping line 103: expected 28 fields, saw 29\nSkipping line 104: expected 28 fields, saw 29\nSkipping line 105: expected 28 fields, saw 29\nSkipping line 106: expected 28 fields, saw 29\nSkipping line 107: expected 28 fields, saw 29\nSkipping line 108: expected 28 fields, saw 29\nSkipping line 109: expected 28 fields, saw 29\nSkipping line 110: expected 28 fields, saw 29\nSkipping line 111: expected 28 fields, saw 29\nSkipping line 112: expected 28 fields, saw 29\nSkipping line 113: expected 28 fields, saw 29\nSkipping line 114: expected 28 fields, saw 29\nSkipping line 116: expected 28 fields, saw 29\nSkipping line 117: expected 28 fields, saw 29\nSkipping line 118: expected 28 fields, saw 29\nSkipping line 119: expected 28 fields, saw 29\nSkipping line 120: expected 28 fields, saw 29\nSkipping line 121: expected 28 fields, saw 29\nSkipping line 122: expected 28 fields, saw 29\nSkipping line 123: expected 28 fields, saw 29\nSkipping line 124: expected 28 fields, saw 29\nSkipping line 125: expected 28 fields, saw 29\nSkipping line 126: expected 28 fields, saw 29\nSkipping line 127: expected 28 fields, saw 29\nSkipping line 128: expected 28 fields, saw 29\nSkipping line 129: expected 28 fields, saw 29\nSkipping line 130: expected 28 fields, saw 29\nSkipping line 131: expected 28 fields, saw 29\nSkipping line 132: expected 28 fields, saw 29\nSkipping line 133: expected 28 fields, saw 29\nSkipping line 134: expected 28 fields, saw 29\nSkipping line 135: expected 28 fields, saw 29\nSkipping line 136: expected 28 fields, saw 29\nSkipping line 137: expected 28 fields, saw 29\nSkipping line 138: expected 28 fields, saw 29\nSkipping line 139: expected 28 fields, saw 29\nSkipping line 140: expected 28 fields, saw 29\nSkipping line 141: expected 28 fields, saw 29\nSkipping line 142: expected 28 fields, saw 29\nSkipping line 143: expected 28 fields, saw 29\nSkipping line 144: expected 28 fields, saw 29\nSkipping line 145: expected 28 fields, saw 29\nSkipping line 146: expected 28 fields, saw 29\nSkipping line 147: expected 28 fields, saw 29\nSkipping line 148: expected 28 fields, saw 29\nSkipping line 149: expected 28 fields, saw 29\nSkipping line 150: expected 28 fields, saw 29\nSkipping line 151: expected 28 fields, saw 29\nSkipping line 152: expected 28 fields, saw 29\nSkipping line 153: expected 28 fields, saw 29\nSkipping line 154: expected 28 fields, saw 29\nSkipping line 155: expected 28 fields, saw 29\nSkipping line 156: expected 28 fields, saw 29\nSkipping line 157: expected 28 fields, saw 29\nSkipping line 158: expected 28 fields, saw 29\nSkipping line 159: expected 28 fields, saw 29\nSkipping line 160: expected 28 fields, saw 29\nSkipping line 161: expected 28 fields, saw 29\nSkipping line 162: expected 28 fields, saw 29\nSkipping line 163: expected 28 fields, saw 29\nSkipping line 164: expected 28 fields, saw 29\nSkipping line 165: expected 28 fields, saw 29\nSkipping line 166: expected 28 fields, saw 29\nSkipping line 167: expected 28 fields, saw 29\nSkipping line 168: expected 28 fields, saw 29\nSkipping line 169: expected 28 fields, saw 29\nSkipping line 170: expected 28 fields, saw 29\nSkipping line 171: expected 28 fields, saw 29\nSkipping line 172: expected 28 fields, saw 29\nSkipping line 173: expected 28 fields, saw 29\nSkipping line 174: expected 28 fields, saw 29\nSkipping line 175: expected 28 fields, saw 29\nSkipping line 176: expected 28 fields, saw 29\nSkipping line 177: expected 28 fields, saw 29\nSkipping line 178: expected 28 fields, saw 29\nSkipping line 179: expected 28 fields, saw 29\nSkipping line 180: expected 28 fields, saw 29\nSkipping line 181: expected 28 fields, saw 29\nSkipping line 182: expected 28 fields, saw 29\nSkipping line 183: expected 28 fields, saw 29\nSkipping line 184: expected 28 fields, saw 29\nSkipping line 185: expected 28 fields, saw 29\nSkipping line 186: expected 28 fields, saw 29\nSkipping line 187: expected 28 fields, saw 29\nSkipping line 188: expected 28 fields, saw 29\nSkipping line 189: expected 28 fields, saw 29\nSkipping line 190: expected 28 fields, saw 29\nSkipping line 191: expected 28 fields, saw 29\nSkipping line 192: expected 28 fields, saw 29\nSkipping line 193: expected 28 fields, saw 29\nSkipping line 194: expected 28 fields, saw 29\nSkipping line 195: expected 28 fields, saw 29\nSkipping line 196: expected 28 fields, saw 29\nSkipping line 197: expected 28 fields, saw 29\nSkipping line 198: expected 28 fields, saw 29\nSkipping line 199: expected 28 fields, saw 29\nSkipping line 200: expected 28 fields, saw 29\nSkipping line 201: expected 28 fields, saw 29\nSkipping line 202: expected 28 fields, saw 29\nSkipping line 203: expected 28 fields, saw 29\nSkipping line 204: expected 28 fields, saw 29\nSkipping line 205: expected 28 fields, saw 29\nSkipping line 206: expected 28 fields, saw 29\nSkipping line 207: expected 28 fields, saw 29\nSkipping line 208: expected 28 fields, saw 29\nSkipping line 209: expected 28 fields, saw 29\nSkipping line 210: expected 28 fields, saw 29\nSkipping line 211: expected 28 fields, saw 29\nSkipping line 212: expected 28 fields, saw 29\nSkipping line 213: expected 28 fields, saw 29\nSkipping line 214: expected 28 fields, saw 29\nSkipping line 215: expected 28 fields, saw 29\nSkipping line 216: expected 28 fields, saw 29\nSkipping line 217: expected 28 fields, saw 29\nSkipping line 218: expected 28 fields, saw 29\nSkipping line 219: expected 28 fields, saw 29\nSkipping line 220: expected 28 fields, saw 29\nSkipping line 221: expected 28 fields, saw 29\nSkipping line 222: expected 28 fields, saw 29\nSkipping line 223: expected 28 fields, saw 29\nSkipping line 224: expected 28 fields, saw 29\nSkipping line 225: expected 28 fields, saw 29\nSkipping line 226: expected 28 fields, saw 29\nSkipping line 227: expected 28 fields, saw 29\nSkipping line 228: expected 28 fields, saw 29\nSkipping line 229: expected 28 fields, saw 29\nSkipping line 230: expected 28 fields, saw 29\nSkipping line 231: expected 28 fields, saw 29\nSkipping line 232: expected 28 fields, saw 29\nSkipping line 233: expected 28 fields, saw 29\nSkipping line 234: expected 28 fields, saw 29\nSkipping line 235: expected 28 fields, saw 29\nSkipping line 236: expected 28 fields, saw 29\nSkipping line 237: expected 28 fields, saw 29\nSkipping line 238: expected 28 fields, saw 29\nSkipping line 239: expected 28 fields, saw 29\nSkipping line 240: expected 28 fields, saw 29\nSkipping line 241: expected 28 fields, saw 29\nSkipping line 242: expected 28 fields, saw 29\nSkipping line 243: expected 28 fields, saw 29\nSkipping line 244: expected 28 fields, saw 29\nSkipping line 245: expected 28 fields, saw 29\nSkipping line 246: expected 28 fields, saw 29\nSkipping line 247: expected 28 fields, saw 29\nSkipping line 248: expected 28 fields, saw 29\nSkipping line 249: expected 28 fields, saw 29\nSkipping line 250: expected 28 fields, saw 29\nSkipping line 251: expected 28 fields, saw 29\nSkipping line 252: expected 28 fields, saw 29\nSkipping line 253: expected 28 fields, saw 29\nSkipping line 254: expected 28 fields, saw 29\nSkipping line 255: expected 28 fields, saw 29\nSkipping line 256: expected 28 fields, saw 29\nSkipping line 257: expected 28 fields, saw 29\nSkipping line 258: expected 28 fields, saw 29\nSkipping line 259: expected 28 fields, saw 29\nSkipping line 260: expected 28 fields, saw 29\nSkipping line 261: expected 28 fields, saw 29\nSkipping line 262: expected 28 fields, saw 29\nSkipping line 263: expected 28 fields, saw 29\nSkipping line 264: expected 28 fields, saw 29\nSkipping line 265: expected 28 fields, saw 29\nSkipping line 266: expected 28 fields, saw 29\nSkipping line 267: expected 28 fields, saw 29\nSkipping line 268: expected 28 fields, saw 29\nSkipping line 269: expected 28 fields, saw 29\nSkipping line 270: expected 28 fields, saw 29\nSkipping line 271: expected 28 fields, saw 29\nSkipping line 272: expected 28 fields, saw 29\nSkipping line 273: expected 28 fields, saw 29\nSkipping line 274: expected 28 fields, saw 29\nSkipping line 275: expected 28 fields, saw 29\nSkipping line 276: expected 28 fields, saw 29\nSkipping line 277: expected 28 fields, saw 29\nSkipping line 278: expected 28 fields, saw 29\nSkipping line 279: expected 28 fields, saw 29\nSkipping line 280: expected 28 fields, saw 29\nSkipping line 281: expected 28 fields, saw 29\nSkipping line 282: expected 28 fields, saw 29\nSkipping line 283: expected 28 fields, saw 29\nSkipping line 284: expected 28 fields, saw 29\nSkipping line 285: expected 28 fields, saw 29\nSkipping line 286: expected 28 fields, saw 29\nSkipping line 300: expected 28 fields, saw 29\n'

None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 28 columns):
0     15 non-null int64
1     15 non-null int64
2     15 non-null int64
3     15 non-null object
4     15 non-null object
5     15 non-null object
6     15 non-null object
7     15 non-null object
8     15 non-null object
9     15 non-null object
10    15 non-null object
11    15 non-null object
12    15 non-null object
13    15 non-null object
14    15 non-null object
15    15 non-null object
16    15 non-null object
17    15 non-null object
18    15 non-null object
19    15 non-null object
20    15 non-null object
21    15 non-null object
22    15 non-null int64
23    15 non-null int64
24    15 non-null int64
25    15 non-null int64
26    15 non-null int64
27    15 non-null int64
dtypes: int64(9), object(19)
memory usage: 3.4+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 20 columns):
0     210 non-null object
1     210 non-null float64
2     210 non-null float64
3     210 non-null int64
4     210 non-null float64
5     210 non-null float64
6     210 non-null float64
7     210 non-null float64
8     210 non-null float64
9     210 non-null float64
10    210 non-null float64
11    210 non-null float64
12    210 non-null float64
13    210 non-null float64
14    210 non-null float64
15    210 non-null float64
16    210 non-null float64
17    210 non-null float64
18    210 non-null float64
19    210 non-null float64
dtypes: float64(18), int64(1), object(1)
memory usage: 32.9+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
0     583 non-null int64
1     583 non-null object
2     583 non-null float64
3     583 non-null float64
4     583 non-null int64
5     583 non-null int64
6     583 non-null int64
7     583 non-null float64
8     583 non-null float64
9     579 non-null float64
10    583 non-null int64
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
0     351 non-null int64
1     351 non-null int64
2     351 non-null float64
3     351 non-null float64
4     351 non-null float64
5     351 non-null float64
6     351 non-null float64
7     351 non-null float64
8     351 non-null float64
9     351 non-null float64
10    351 non-null float64
11    351 non-null float64
12    351 non-null float64
13    351 non-null float64
14    351 non-null float64
15    351 non-null float64
16    351 non-null float64
17    351 non-null float64
18    351 non-null float64
19    351 non-null float64
20    351 non-null float64
21    351 non-null float64
22    351 non-null float64
23    351 non-null float64
24    351 non-null float64
25    351 non-null float64
26    351 non-null float64
27    351 non-null float64
28    351 non-null float64
29    351 non-null float64
30    351 non-null float64
31    351 non-null float64
32    351 non-null float64
33    351 non-null float64
34    351 non-null object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
0    150 non-null float64
1    150 non-null float64
2    150 non-null float64
3    150 non-null float64
4    150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 11 columns):
0     24 non-null int64
1     15 non-null float64
2     9 non-null float64
3     15 non-null float64
4     9 non-null float64
5     15 non-null float64
6     9 non-null float64
7     15 non-null float64
8     9 non-null float64
9     15 non-null float64
10    9 non-null float64
dtypes: float64(10), int64(1)
memory usage: 2.1 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
0     20000 non-null object
1     20000 non-null int64
2     20000 non-null int64
3     20000 non-null int64
4     20000 non-null int64
5     20000 non-null int64
6     20000 non-null int64
7     20000 non-null int64
8     20000 non-null int64
9     20000 non-null int64
10    20000 non-null int64
11    20000 non-null int64
12    20000 non-null int64
13    20000 non-null int64
14    20000 non-null int64
15    20000 non-null int64
16    20000 non-null int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 91 columns):
0     360 non-null float64
1     360 non-null float64
2     360 non-null float64
3     360 non-null float64
4     360 non-null float64
5     360 non-null float64
6     360 non-null float64
7     360 non-null float64
8     360 non-null float64
9     360 non-null float64
10    360 non-null float64
11    360 non-null float64
12    360 non-null float64
13    360 non-null float64
14    360 non-null float64
15    360 non-null float64
16    360 non-null float64
17    360 non-null float64
18    360 non-null float64
19    360 non-null float64
20    360 non-null float64
21    360 non-null float64
22    360 non-null float64
23    360 non-null float64
24    360 non-null float64
25    360 non-null float64
26    360 non-null float64
27    360 non-null float64
28    360 non-null float64
29    360 non-null float64
30    360 non-null float64
31    360 non-null float64
32    360 non-null float64
33    360 non-null float64
34    360 non-null float64
35    360 non-null float64
36    360 non-null float64
37    360 non-null float64
38    360 non-null float64
39    360 non-null float64
40    360 non-null float64
41    360 non-null float64
42    360 non-null float64
43    360 non-null float64
44    360 non-null float64
45    360 non-null float64
46    360 non-null float64
47    360 non-null float64
48    360 non-null float64
49    360 non-null float64
50    360 non-null float64
51    360 non-null float64
52    360 non-null float64
53    360 non-null float64
54    360 non-null float64
55    360 non-null float64
56    360 non-null float64
57    360 non-null float64
58    360 non-null float64
59    360 non-null float64
60    360 non-null float64
61    360 non-null float64
62    360 non-null float64
63    360 non-null float64
64    360 non-null float64
65    360 non-null float64
66    360 non-null float64
67    360 non-null float64
68    360 non-null float64
69    360 non-null float64
70    360 non-null float64
71    360 non-null float64
72    360 non-null float64
73    360 non-null float64
74    360 non-null float64
75    360 non-null float64
76    360 non-null float64
77    360 non-null float64
78    360 non-null float64
79    360 non-null float64
80    360 non-null float64
81    360 non-null float64
82    360 non-null float64
83    360 non-null float64
84    360 non-null float64
85    360 non-null float64
86    360 non-null float64
87    360 non-null float64
88    360 non-null float64
89    360 non-null float64
90    360 non-null int64
dtypes: float64(90), int64(1)
memory usage: 256.0 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 57 columns):
0     32 non-null int64
1     32 non-null int64
2     32 non-null int64
3     32 non-null int64
4     32 non-null object
5     32 non-null int64
6     32 non-null int64
7     32 non-null int64
8     32 non-null int64
9     32 non-null int64
10    32 non-null int64
11    32 non-null int64
12    32 non-null int64
13    32 non-null int64
14    32 non-null int64
15    32 non-null int64
16    32 non-null int64
17    32 non-null int64
18    32 non-null int64
19    32 non-null int64
20    32 non-null int64
21    32 non-null int64
22    32 non-null int64
23    32 non-null int64
24    32 non-null int64
25    32 non-null int64
26    32 non-null int64
27    32 non-null int64
28    32 non-null int64
29    32 non-null int64
30    32 non-null int64
31    32 non-null int64
32    32 non-null int64
33    32 non-null int64
34    32 non-null int64
35    32 non-null int64
36    32 non-null int64
37    32 non-null int64
38    32 non-null object
39    32 non-null int64
40    32 non-null int64
41    32 non-null int64
42    32 non-null int64
43    32 non-null int64
44    32 non-null int64
45    32 non-null int64
46    32 non-null int64
47    32 non-null int64
48    32 non-null int64
49    32 non-null int64
50    32 non-null int64
51    32 non-null int64
52    32 non-null int64
53    32 non-null int64
54    32 non-null int64
55    32 non-null int64
56    32 non-null int64
dtypes: int64(55), object(2)
memory usage: 14.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
0     19020 non-null float64
1     19020 non-null float64
2     19020 non-null float64
3     19020 non-null float64
4     19020 non-null float64
5     19020 non-null float64
6     19020 non-null float64
7     19020 non-null float64
8     19020 non-null float64
9     19020 non-null float64
10    19020 non-null object
dtypes: float64(10), object(1)
memory usage: 1.6+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
0    961 non-null object
1    961 non-null object
2    961 non-null object
3    961 non-null object
4    961 non-null object
5    961 non-null int64
dtypes: int64(1), object(5)
memory usage: 45.1+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 9 columns):
0    0 non-null float64
1    124 non-null int64
2    124 non-null int64
3    124 non-null int64
4    124 non-null int64
5    124 non-null int64
6    124 non-null int64
7    124 non-null int64
8    124 non-null object
dtypes: float64(1), int64(7), object(1)
memory usage: 8.8+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 9 columns):
0    0 non-null float64
1    169 non-null int64
2    169 non-null int64
3    169 non-null int64
4    169 non-null int64
5    169 non-null int64
6    169 non-null int64
7    169 non-null int64
8    169 non-null object
dtypes: float64(1), int64(7), object(1)
memory usage: 12.0+ KB

None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 9 columns):
0    0 non-null float64
1    122 non-null int64
2    122 non-null int64
3    122 non-null int64
4    122 non-null int64
5    122 non-null int64
6    122 non-null int64
7    122 non-null int64
8    122 non-null object
dtypes: float64(1), int64(7), object(1)
memory usage: 8.7+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
0     8124 non-null object
1     8124 non-null object
2     8124 non-null object
3     8124 non-null object
4     8124 non-null object
5     8124 non-null object
6     8124 non-null object
7     8124 non-null object
8     8124 non-null object
9     8124 non-null object
10    8124 non-null object
11    8124 non-null object
12    8124 non-null object
13    8124 non-null object
14    8124 non-null object
15    8124 non-null object
16    8124 non-null object
17    8124 non-null object
18    8124 non-null object
19    8124 non-null object
20    8124 non-null object
21    8124 non-null object
22    8124 non-null object
dtypes: object(23)
memory usage: 1.4+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12960 entries, 0 to 12959
Data columns (total 9 columns):
0    12960 non-null object
1    12960 non-null object
2    12960 non-null object
3    12960 non-null object
4    12960 non-null object
5    12960 non-null object
6    12960 non-null object
7    12960 non-null object
8    12960 non-null object
dtypes: object(9)
memory usage: 911.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3823 entries, 0 to 3822
Data columns (total 65 columns):
0     3823 non-null int64
1     3823 non-null int64
2     3823 non-null int64
3     3823 non-null int64
4     3823 non-null int64
5     3823 non-null int64
6     3823 non-null int64
7     3823 non-null int64
8     3823 non-null int64
9     3823 non-null int64
10    3823 non-null int64
11    3823 non-null int64
12    3823 non-null int64
13    3823 non-null int64
14    3823 non-null int64
15    3823 non-null int64
16    3823 non-null int64
17    3823 non-null int64
18    3823 non-null int64
19    3823 non-null int64
20    3823 non-null int64
21    3823 non-null int64
22    3823 non-null int64
23    3823 non-null int64
24    3823 non-null int64
25    3823 non-null int64
26    3823 non-null int64
27    3823 non-null int64
28    3823 non-null int64
29    3823 non-null int64
30    3823 non-null int64
31    3823 non-null int64
32    3823 non-null int64
33    3823 non-null int64
34    3823 non-null int64
35    3823 non-null int64
36    3823 non-null int64
37    3823 non-null int64
38    3823 non-null int64
39    3823 non-null int64
40    3823 non-null int64
41    3823 non-null int64
42    3823 non-null int64
43    3823 non-null int64
44    3823 non-null int64
45    3823 non-null int64
46    3823 non-null int64
47    3823 non-null int64
48    3823 non-null int64
49    3823 non-null int64
50    3823 non-null int64
51    3823 non-null int64
52    3823 non-null int64
53    3823 non-null int64
54    3823 non-null int64
55    3823 non-null int64
56    3823 non-null int64
57    3823 non-null int64
58    3823 non-null int64
59    3823 non-null int64
60    3823 non-null int64
61    3823 non-null int64
62    3823 non-null int64
63    3823 non-null int64
64    3823 non-null int64
dtypes: int64(65)
memory usage: 1.9 MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2534 entries, 0 to 2533
Data columns (total 74 columns):
0     2534 non-null object
1     2534 non-null object
2     2534 non-null object
3     2534 non-null object
4     2534 non-null object
5     2534 non-null object
6     2534 non-null object
7     2534 non-null object
8     2534 non-null object
9     2534 non-null object
10    2534 non-null object
11    2534 non-null object
12    2534 non-null object
13    2534 non-null object
14    2534 non-null object
15    2534 non-null object
16    2534 non-null object
17    2534 non-null object
18    2534 non-null object
19    2534 non-null object
20    2534 non-null object
21    2534 non-null object
22    2534 non-null object
23    2534 non-null object
24    2534 non-null object
25    2534 non-null object
26    2534 non-null object
27    2534 non-null object
28    2534 non-null object
29    2534 non-null object
30    2534 non-null object
31    2534 non-null object
32    2534 non-null object
33    2534 non-null object
34    2534 non-null object
35    2534 non-null object
36    2534 non-null object
37    2534 non-null object
38    2534 non-null object
39    2534 non-null object
40    2534 non-null object
41    2534 non-null object
42    2534 non-null object
43    2534 non-null object
44    2534 non-null object
45    2534 non-null object
46    2534 non-null object
47    2534 non-null object
48    2534 non-null object
49    2534 non-null object
50    2534 non-null object
51    2534 non-null object
52    2534 non-null object
53    2534 non-null object
54    2534 non-null object
55    2534 non-null object
56    2534 non-null object
57    2534 non-null object
58    2534 non-null object
59    2534 non-null object
60    2534 non-null object
61    2534 non-null object
62    2534 non-null object
63    2534 non-null object
64    2534 non-null object
65    2534 non-null object
66    2534 non-null object
67    2534 non-null object
68    2534 non-null object
69    2534 non-null object
70    2534 non-null object
71    2534 non-null object
72    2534 non-null object
73    2534 non-null float64
dtypes: float64(1), object(73)
memory usage: 1.4+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2536 entries, 0 to 2535
Data columns (total 74 columns):
0     2536 non-null object
1     2536 non-null object
2     2536 non-null object
3     2536 non-null object
4     2536 non-null object
5     2536 non-null object
6     2536 non-null object
7     2536 non-null object
8     2536 non-null object
9     2536 non-null object
10    2536 non-null object
11    2536 non-null object
12    2536 non-null object
13    2536 non-null object
14    2536 non-null object
15    2536 non-null object
16    2536 non-null object
17    2536 non-null object
18    2536 non-null object
19    2536 non-null object
20    2536 non-null object
21    2536 non-null object
22    2536 non-null object
23    2536 non-null object
24    2536 non-null object
25    2536 non-null object
26    2536 non-null object
27    2536 non-null object
28    2536 non-null object
29    2536 non-null object
30    2536 non-null object
31    2536 non-null object
32    2536 non-null object
33    2536 non-null object
34    2536 non-null object
35    2536 non-null object
36    2536 non-null object
37    2536 non-null object
38    2536 non-null object
39    2536 non-null object
40    2536 non-null object
41    2536 non-null object
42    2536 non-null object
43    2536 non-null object
44    2536 non-null object
45    2536 non-null object
46    2536 non-null object
47    2536 non-null object
48    2536 non-null object
49    2536 non-null object
50    2536 non-null object
51    2536 non-null object
52    2536 non-null object
53    2536 non-null object
54    2536 non-null object
55    2536 non-null object
56    2536 non-null object
57    2536 non-null object
58    2536 non-null object
59    2536 non-null object
60    2536 non-null object
61    2536 non-null object
62    2536 non-null object
63    2536 non-null object
64    2536 non-null object
65    2536 non-null object
66    2536 non-null object
67    2536 non-null object
68    2536 non-null object
69    2536 non-null object
70    2536 non-null object
71    2536 non-null object
72    2536 non-null object
73    2536 non-null float64
dtypes: float64(1), object(73)
memory usage: 1.4+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
0     195 non-null object
1     195 non-null float64
2     195 non-null float64
3     195 non-null float64
4     195 non-null float64
5     195 non-null float64
6     195 non-null float64
7     195 non-null float64
8     195 non-null float64
9     195 non-null float64
10    195 non-null float64
11    195 non-null float64
12    195 non-null float64
13    195 non-null float64
14    195 non-null float64
15    195 non-null float64
16    195 non-null float64
17    195 non-null int64
18    195 non-null float64
19    195 non-null float64
20    195 non-null float64
21    195 non-null float64
22    195 non-null float64
23    195 non-null float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7494 entries, 0 to 7493
Data columns (total 17 columns):
0     7494 non-null int64
1     7494 non-null int64
2     7494 non-null int64
3     7494 non-null int64
4     7494 non-null int64
5     7494 non-null int64
6     7494 non-null int64
7     7494 non-null int64
8     7494 non-null int64
9     7494 non-null int64
10    7494 non-null int64
11    7494 non-null int64
12    7494 non-null int64
13    7494 non-null int64
14    7494 non-null int64
15    7494 non-null int64
16    7494 non-null int64
dtypes: int64(17)
memory usage: 995.4 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
0    768 non-null int64
1    768 non-null int64
2    768 non-null int64
3    768 non-null int64
4    768 non-null int64
5    768 non-null float64
6    768 non-null float64
7    768 non-null int64
8    768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 14 columns):
0     182 non-null float64
1     182 non-null float64
2     182 non-null float64
3     182 non-null float64
4     182 non-null float64
5     182 non-null float64
6     182 non-null float64
7     182 non-null float64
8     182 non-null float64
9     182 non-null float64
10    182 non-null float64
11    182 non-null float64
12    182 non-null float64
13    0 non-null float64
dtypes: float64(14)
memory usage: 20.0 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25010 entries, 0 to 25009
Data columns (total 11 columns):
0     25010 non-null int64
1     25010 non-null int64
2     25010 non-null int64
3     25010 non-null int64
4     25010 non-null int64
5     25010 non-null int64
6     25010 non-null int64
7     25010 non-null int64
8     25010 non-null int64
9     25010 non-null int64
10    25010 non-null int64
dtypes: int64(11)
memory usage: 2.1 MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 9 columns):
0    90 non-null object
1    90 non-null object
2    90 non-null object
3    90 non-null object
4    90 non-null object
5    90 non-null object
6    90 non-null object
7    90 non-null object
8    90 non-null object
dtypes: object(9)
memory usage: 6.4+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 42 columns):
0     1055 non-null float64
1     1055 non-null float64
2     1055 non-null int64
3     1055 non-null int64
4     1055 non-null int64
5     1055 non-null int64
6     1055 non-null int64
7     1055 non-null float64
8     1055 non-null int64
9     1055 non-null int64
10    1055 non-null int64
11    1055 non-null float64
12    1055 non-null float64
13    1055 non-null float64
14    1055 non-null float64
15    1055 non-null int64
16    1055 non-null float64
17    1055 non-null float64
18    1055 non-null int64
19    1055 non-null int64
20    1055 non-null int64
21    1055 non-null float64
22    1055 non-null int64
23    1055 non-null int64
24    1055 non-null int64
25    1055 non-null int64
26    1055 non-null float64
27    1055 non-null float64
28    1055 non-null int64
29    1055 non-null float64
30    1055 non-null float64
31    1055 non-null int64
32    1055 non-null int64
33    1055 non-null int64
34    1055 non-null int64
35    1055 non-null float64
36    1055 non-null float64
37    1055 non-null int64
38    1055 non-null float64
39    1055 non-null int64
40    1055 non-null int64
41    1055 non-null object
dtypes: float64(17), int64(24), object(1)
memory usage: 346.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 8 columns):
0    199 non-null float64
1    199 non-null float64
2    199 non-null float64
3    199 non-null float64
4    199 non-null float64
5    199 non-null float64
6    199 non-null float64
7    199 non-null int64
dtypes: float64(7), int64(1)
memory usage: 12.5 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 19 columns):
0     2584 non-null object
1     2584 non-null object
2     2584 non-null object
3     2584 non-null int64
4     2584 non-null int64
5     2584 non-null int64
6     2584 non-null int64
7     2584 non-null object
8     2584 non-null int64
9     2584 non-null int64
10    2584 non-null int64
11    2584 non-null int64
12    2584 non-null int64
13    2584 non-null int64
14    2584 non-null int64
15    2584 non-null int64
16    2584 non-null int64
17    2584 non-null int64
18    2584 non-null int64
dtypes: int64(15), object(4)
memory usage: 383.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
0    15 non-null int64
1    15 non-null object
2    15 non-null object
3    15 non-null object
4    15 non-null object
5    15 non-null object
6    15 non-null int64
dtypes: int64(2), object(5)
memory usage: 920.0+ bytes
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>

b'Skipping line 8: expected 8 fields, saw 10\nSkipping line 36: expected 8 fields, saw 10\nSkipping line 61: expected 8 fields, saw 9\nSkipping line 69: expected 8 fields, saw 9\nSkipping line 107: expected 8 fields, saw 9\nSkipping line 136: expected 8 fields, saw 9\nSkipping line 170: expected 8 fields, saw 9\nSkipping line 171: expected 8 fields, saw 9\nSkipping line 173: expected 8 fields, saw 9\nSkipping line 202: expected 8 fields, saw 9\nSkipping line 204: expected 8 fields, saw 9\n'

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245057 entries, 0 to 245056
Data columns (total 4 columns):
0    245057 non-null int64
1    245057 non-null int64
2    245057 non-null int64
3    245057 non-null int64
dtypes: int64(4)
memory usage: 7.5 MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 36 columns):
0     307 non-null object
1     307 non-null object
2     307 non-null object
3     307 non-null object
4     307 non-null object
5     307 non-null object
6     307 non-null object
7     307 non-null object
8     307 non-null object
9     307 non-null object
10    307 non-null object
11    307 non-null object
12    307 non-null int64
13    307 non-null object
14    307 non-null object
15    307 non-null object
16    307 non-null object
17    307 non-null object
18    307 non-null object
19    307 non-null object
20    307 non-null object
21    307 non-null object
22    307 non-null object
23    307 non-null object
24    307 non-null object
25    307 non-null object
26    307 non-null object
27    307 non-null object
28    307 non-null object
29    307 non-null object
30    307 non-null object
31    307 non-null object
32    307 non-null object
33    307 non-null object
34    307 non-null object
35    307 non-null object
dtypes: int64(1), object(35)
memory usage: 86.4+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 36 columns):
0     47 non-null int64
1     47 non-null int64
2     47 non-null int64
3     47 non-null int64
4     47 non-null int64
5     47 non-null int64
6     47 non-null int64
7     47 non-null int64
8     47 non-null int64
9     47 non-null int64
10    47 non-null int64
11    47 non-null int64
12    47 non-null int64
13    47 non-null int64
14    47 non-null int64
15    47 non-null int64
16    47 non-null int64
17    47 non-null int64
18    47 non-null int64
19    47 non-null int64
20    47 non-null int64
21    47 non-null int64
22    47 non-null int64
23    47 non-null int64
24    47 non-null int64
25    47 non-null int64
26    47 non-null int64
27    47 non-null int64
28    47 non-null int64
29    47 non-null int64
30    47 non-null int64
31    47 non-null int64
32    47 non-null int64
33    47 non-null int64
34    47 non-null int64
35    47 non-null object
dtypes: int64(35), object(1)
memory usage: 13.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
0     4601 non-null float64
1     4601 non-null float64
2     4601 non-null float64
3     4601 non-null float64
4     4601 non-null float64
5     4601 non-null float64
6     4601 non-null float64
7     4601 non-null float64
8     4601 non-null float64
9     4601 non-null float64
10    4601 non-null float64
11    4601 non-null float64
12    4601 non-null float64
13    4601 non-null float64
14    4601 non-null float64
15    4601 non-null float64
16    4601 non-null float64
17    4601 non-null float64
18    4601 non-null float64
19    4601 non-null float64
20    4601 non-null float64
21    4601 non-null float64
22    4601 non-null float64
23    4601 non-null float64
24    4601 non-null float64
25    4601 non-null float64
26    4601 non-null float64
27    4601 non-null float64
28    4601 non-null float64
29    4601 non-null float64
30    4601 non-null float64
31    4601 non-null float64
32    4601 non-null float64
33    4601 non-null float64
34    4601 non-null float64
35    4601 non-null float64
36    4601 non-null float64
37    4601 non-null float64
38    4601 non-null float64
39    4601 non-null float64
40    4601 non-null float64
41    4601 non-null float64
42    4601 non-null float64
43    4601 non-null float64
44    4601 non-null float64
45    4601 non-null float64
46    4601 non-null float64
47    4601 non-null float64
48    4601 non-null float64
49    4601 non-null float64
50    4601 non-null float64
51    4601 non-null float64
52    4601 non-null float64
53    4601 non-null float64
54    4601 non-null float64
55    4601 non-null int64
56    4601 non-null int64
57    4601 non-null int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 23 columns):
0     80 non-null int64
1     80 non-null int64
2     80 non-null int64
3     80 non-null int64
4     80 non-null int64
5     80 non-null int64
6     80 non-null int64
7     80 non-null int64
8     80 non-null int64
9     80 non-null int64
10    80 non-null int64
11    80 non-null int64
12    80 non-null int64
13    80 non-null int64
14    80 non-null int64
15    80 non-null int64
16    80 non-null int64
17    80 non-null int64
18    80 non-null int64
19    80 non-null int64
20    80 non-null int64
21    80 non-null int64
22    80 non-null int64
dtypes: int64(23)
memory usage: 14.5 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 45 columns):
0     80 non-null int64
1     80 non-null int64
2     80 non-null int64
3     80 non-null int64
4     80 non-null int64
5     80 non-null int64
6     80 non-null int64
7     80 non-null int64
8     80 non-null int64
9     80 non-null int64
10    80 non-null int64
11    80 non-null int64
12    80 non-null int64
13    80 non-null int64
14    80 non-null int64
15    80 non-null int64
16    80 non-null int64
17    80 non-null int64
18    80 non-null int64
19    80 non-null int64
20    80 non-null int64
21    80 non-null int64
22    80 non-null int64
23    80 non-null int64
24    80 non-null int64
25    80 non-null int64
26    80 non-null int64
27    80 non-null int64
28    80 non-null int64
29    80 non-null int64
30    80 non-null int64
31    80 non-null int64
32    80 non-null int64
33    80 non-null int64
34    80 non-null int64
35    80 non-null int64
36    80 non-null int64
37    80 non-null int64
38    80 non-null int64
39    80 non-null int64
40    80 non-null int64
41    80 non-null int64
42    80 non-null int64
43    80 non-null int64
44    80 non-null int64
dtypes: int64(45)
memory usage: 28.2 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
0     1000 non-null object
1     1000 non-null int64
2     1000 non-null object
3     1000 non-null object
4     1000 non-null int64
5     1000 non-null object
6     1000 non-null object
7     1000 non-null int64
8     1000 non-null object
9     1000 non-null object
10    1000 non-null int64
11    1000 non-null object
12    1000 non-null int64
13    1000 non-null object
14    1000 non-null object
15    1000 non-null int64
16    1000 non-null object
17    1000 non-null int64
18    1000 non-null object
19    1000 non-null object
20    1000 non-null int64
dtypes: int64(8), object(13)
memory usage: 164.1+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4435 entries, 0 to 4434
Data columns (total 37 columns):
0     4435 non-null int64
1     4435 non-null int64
2     4435 non-null int64
3     4435 non-null int64
4     4435 non-null int64
5     4435 non-null int64
6     4435 non-null int64
7     4435 non-null int64
8     4435 non-null int64
9     4435 non-null int64
10    4435 non-null int64
11    4435 non-null int64
12    4435 non-null int64
13    4435 non-null int64
14    4435 non-null int64
15    4435 non-null int64
16    4435 non-null int64
17    4435 non-null int64
18    4435 non-null int64
19    4435 non-null int64
20    4435 non-null int64
21    4435 non-null int64
22    4435 non-null int64
23    4435 non-null int64
24    4435 non-null int64
25    4435 non-null int64
26    4435 non-null int64
27    4435 non-null int64
28    4435 non-null int64
29    4435 non-null int64
30    4435 non-null int64
31    4435 non-null int64
32    4435 non-null int64
33    4435 non-null int64
34    4435 non-null int64
35    4435 non-null int64
36    4435 non-null int64
dtypes: int64(37)
memory usage: 1.3 MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 6 columns):
0    151 non-null int64
1    151 non-null int64
2    151 non-null int64
3    151 non-null int64
4    151 non-null int64
5    151 non-null int64
dtypes: int64(6)
memory usage: 7.2 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 17 columns):
0     470 non-null object
1     470 non-null float64
2     470 non-null float64
3     470 non-null object
4     470 non-null object
5     470 non-null object
6     470 non-null object
7     470 non-null object
8     470 non-null object
9     470 non-null object
10    470 non-null object
11    470 non-null object
12    470 non-null object
13    470 non-null object
14    470 non-null object
15    470 non-null int64
16    470 non-null object
dtypes: float64(2), int64(1), object(14)
memory usage: 62.5+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 31 columns):
0     2800 non-null object
1     2800 non-null object
2     2800 non-null object
3     2800 non-null object
4     2800 non-null object
5     2800 non-null object
6     2800 non-null object
7     2800 non-null object
8     2800 non-null object
9     2800 non-null object
10    2800 non-null object
11    2800 non-null object
12    2800 non-null object
13    2800 non-null object
14    2800 non-null object
15    2800 non-null object
16    2800 non-null object
17    2800 non-null object
18    2800 non-null object
19    2800 non-null object
20    2800 non-null object
21    2800 non-null object
22    2800 non-null object
23    2800 non-null object
24    2800 non-null object
25    2800 non-null object
26    2800 non-null object
27    2800 non-null object
28    2800 non-null object
29    2800 non-null object
30    2800 non-null int64
dtypes: int64(1), object(30)
memory usage: 678.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 31 columns):
0     2800 non-null object
1     2800 non-null object
2     2800 non-null object
3     2800 non-null object
4     2800 non-null object
5     2800 non-null object
6     2800 non-null object
7     2800 non-null object
8     2800 non-null object
9     2800 non-null object
10    2800 non-null object
11    2800 non-null object
12    2800 non-null object
13    2800 non-null object
14    2800 non-null object
15    2800 non-null object
16    2800 non-null object
17    2800 non-null object
18    2800 non-null object
19    2800 non-null object
20    2800 non-null object
21    2800 non-null object
22    2800 non-null object
23    2800 non-null object
24    2800 non-null object
25    2800 non-null object
26    2800 non-null object
27    2800 non-null object
28    2800 non-null object
29    2800 non-null object
30    2800 non-null int64
dtypes: int64(1), object(30)
memory usage: 678.2+ KB

None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 31 columns):
0     2800 non-null object
1     2800 non-null object
2     2800 non-null object
3     2800 non-null object
4     2800 non-null object
5     2800 non-null object
6     2800 non-null object
7     2800 non-null object
8     2800 non-null object
9     2800 non-null object
10    2800 non-null object
11    2800 non-null object
12    2800 non-null object
13    2800 non-null object
14    2800 non-null object
15    2800 non-null object
16    2800 non-null object
17    2800 non-null object
18    2800 non-null object
19    2800 non-null object
20    2800 non-null object
21    2800 non-null object
22    2800 non-null object
23    2800 non-null object
24    2800 non-null object
25    2800 non-null object
26    2800 non-null object
27    2800 non-null object
28    2800 non-null object
29    2800 non-null object
30    2800 non-null int64
dtypes: int64(1), object(30)
memory usage: 678.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 31 columns):
0     2800 non-null object
1     2800 non-null object
2     2800 non-null object
3     2800 non-null object
4     2800 non-null object
5     2800 non-null object
6     2800 non-null object
7     2800 non-null object
8     2800 non-null object
9     2800 non-null object
10    2800 non-null object
11    2800 non-null object
12    2800 non-null object
13    2800 non-null object
14    2800 non-null object
15    2800 non-null object
16    2800 non-null object
17    2800 non-null object
18    2800 non-null object
19    2800 non-null object
20    2800 non-null object
21    2800 non-null object
22    2800 non-null object
23    2800 non-null object
24    2800 non-null object
25    2800 non-null object
26    2800 non-null object
27    2800 non-null object
28    2800 non-null object
29    2800 non-null object
30    2800 non-null int64
dtypes: int64(1), object(30)
memory usage: 678.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3772 entries, 0 to 3771
Data columns (total 24 columns):
0     3772 non-null float64
1     3772 non-null int64
2     3772 non-null int64
3     3772 non-null int64
4     3772 non-null int64
5     3772 non-null int64
6     3772 non-null int64
7     3772 non-null int64
8     3772 non-null int64
9     3772 non-null int64
10    3772 non-null int64
11    3772 non-null int64
12    3772 non-null int64
13    3772 non-null int64
14    3772 non-null int64
15    3772 non-null int64
16    3772 non-null float64
17    3772 non-null float64
18    3772 non-null float64
19    3772 non-null float64
20    3772 non-null float64
21    3772 non-null int64
22    0 non-null float64
23    0 non-null float64
dtypes: float64(8), int64(16)
memory usage: 707.3 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 31 columns):
0     2800 non-null object
1     2800 non-null object
2     2800 non-null object
3     2800 non-null object
4     2800 non-null object
5     2800 non-null object
6     2800 non-null object
7     2800 non-null object
8     2800 non-null object
9     2800 non-null object
10    2800 non-null object
11    2800 non-null object
12    2800 non-null object
13    2800 non-null object
14    2800 non-null object
15    2800 non-null object
16    2800 non-null object
17    2800 non-null object
18    2800 non-null object
19    2800 non-null object
20    2800 non-null object
21    2800 non-null object
22    2800 non-null object
23    2800 non-null object
24    2800 non-null object
25    2800 non-null object
26    2800 non-null object
27    2800 non-null object
28    2800 non-null object
29    2800 non-null object
30    2800 non-null int64
dtypes: int64(1), object(30)
memory usage: 678.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 6 columns):
0    215 non-null int64
1    215 non-null int64
2    215 non-null float64
3    215 non-null float64
4    215 non-null float64
5    215 non-null float64
dtypes: float64(4), int64(2)
memory usage: 10.2 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3163 entries, 0 to 3162
Data columns (total 26 columns):
0     3163 non-null object
1     3163 non-null object
2     3163 non-null object
3     3163 non-null object
4     3163 non-null object
5     3163 non-null object
6     3163 non-null object
7     3163 non-null object
8     3163 non-null object
9     3163 non-null object
10    3163 non-null object
11    3163 non-null object
12    3163 non-null object
13    3163 non-null object
14    3163 non-null object
15    3163 non-null object
16    3163 non-null object
17    3163 non-null object
18    3163 non-null object
19    3163 non-null object
20    3163 non-null object
21    3163 non-null object
22    3163 non-null object
23    3163 non-null object
24    3163 non-null object
25    3163 non-null object
dtypes: object(26)
memory usage: 642.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 31 columns):
0     2800 non-null object
1     2800 non-null object
2     2800 non-null object
3     2800 non-null object
4     2800 non-null object
5     2800 non-null object
6     2800 non-null object
7     2800 non-null object
8     2800 non-null object
9     2800 non-null object
10    2800 non-null object
11    2800 non-null object
12    2800 non-null object
13    2800 non-null object
14    2800 non-null object
15    2800 non-null object
16    2800 non-null object
17    2800 non-null object
18    2800 non-null object
19    2800 non-null object
20    2800 non-null object
21    2800 non-null object
22    2800 non-null object
23    2800 non-null object
24    2800 non-null object
25    2800 non-null object
26    2800 non-null object
27    2800 non-null object
28    2800 non-null object
29    2800 non-null object
30    2800 non-null int64
dtypes: int64(1), object(30)
memory usage: 678.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9172 entries, 0 to 9171
Data columns (total 31 columns):
0     9172 non-null int64
1     9172 non-null object
2     9172 non-null object
3     9172 non-null object
4     9172 non-null object
5     9172 non-null object
6     9172 non-null object
7     9172 non-null object
8     9172 non-null object
9     9172 non-null object
10    9172 non-null object
11    9172 non-null object
12    9172 non-null object
13    9172 non-null object
14    9172 non-null object
15    9172 non-null object
16    9172 non-null object
17    9172 non-null object
18    9172 non-null object
19    9172 non-null object
20    9172 non-null object
21    9172 non-null object
22    9172 non-null object
23    9172 non-null object
24    9172 non-null object
25    9172 non-null object
26    9172 non-null object
27    9172 non-null object
28    9172 non-null object
29    9172 non-null object
30    9172 non-null int64
dtypes: int64(2), object(29)
memory usage: 2.2+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
0    958 non-null object
1    958 non-null object
2    958 non-null object
3    958 non-null object
4    958 non-null object
5    958 non-null object
6    958 non-null object
7    958 non-null object
8    958 non-null object
9    958 non-null object
dtypes: object(10)
memory usage: 74.9+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 34 columns):
0     9 non-null int64
1     9 non-null int64
2     9 non-null int64
3     9 non-null object
4     7 non-null object
5     9 non-null object
6     9 non-null object
7     9 non-null object
8     9 non-null object
9     7 non-null object
10    9 non-null object
11    9 non-null object
12    9 non-null object
13    9 non-null object
14    6 non-null object
15    9 non-null object
16    9 non-null object
17    9 non-null object
18    9 non-null object
19    9 non-null object
20    9 non-null object
21    9 non-null object
22    9 non-null object
23    9 non-null int64
24    9 non-null int64
25    9 non-null int64
26    9 non-null int64
27    9 non-null int64
28    9 non-null int64
29    9 non-null int64
30    9 non-null int64
31    9 non-null int64
32    9 non-null object
33    7 non-null object
dtypes: int64(12), object(22)
memory usage: 2.5+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 25 columns):
0     5456 non-null float64
1     5456 non-null float64
2     5456 non-null float64
3     5456 non-null float64
4     5456 non-null float64
5     5456 non-null float64
6     5456 non-null float64
7     5456 non-null float64
8     5456 non-null float64
9     5456 non-null float64
10    5456 non-null float64
11    5456 non-null float64
12    5456 non-null float64
13    5456 non-null float64
14    5456 non-null float64
15    5456 non-null float64
16    5456 non-null float64
17    5456 non-null float64
18    5456 non-null float64
19    5456 non-null float64
20    5456 non-null float64
21    5456 non-null float64
22    5456 non-null float64
23    5456 non-null float64
24    5456 non-null object
dtypes: float64(24), object(1)
memory usage: 1.0+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 3 columns):
0    5456 non-null float64
1    5456 non-null float64
2    5456 non-null object
dtypes: float64(2), object(1)
memory usage: 128.0+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 5 columns):
0    5456 non-null float64
1    5456 non-null float64
2    5456 non-null float64
3    5456 non-null float64
4    5456 non-null object
dtypes: float64(4), object(1)
memory usage: 213.2+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Columns: 159 entries, 0 to 158
dtypes: float64(103), int64(31), object(25)
memory usage: 4.9+ MB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
0     178 non-null int64
1     178 non-null float64
2     178 non-null float64
3     178 non-null float64
4     178 non-null float64
5     178 non-null int64
6     178 non-null float64
7     178 non-null float64
8     178 non-null float64
9     178 non-null float64
10    178 non-null float64
11    178 non-null float64
12    178 non-null float64
13    178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.5 KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1418 entries, 0 to 1417
Data columns (total 19 columns):
0     1418 non-null object
1     0 non-null float64
2     1418 non-null float64
3     0 non-null float64
4     1418 non-null float64
5     0 non-null float64
6     1418 non-null float64
7     0 non-null float64
8     1418 non-null float64
9     0 non-null float64
10    1418 non-null float64
11    0 non-null float64
12    1418 non-null float64
13    0 non-null float64
14    1418 non-null float64
15    0 non-null float64
16    1418 non-null float64
17    0 non-null float64
18    1418 non-null object
dtypes: float64(17), object(2)
memory usage: 210.6+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
0     101 non-null object
1     101 non-null int64
2     101 non-null int64
3     101 non-null int64
4     101 non-null int64
5     101 non-null int64
6     101 non-null int64
7     101 non-null int64
8     101 non-null int64
9     101 non-null int64
10    101 non-null int64
11    101 non-null int64
12    101 non-null int64
13    101 non-null int64
14    101 non-null int64
15    101 non-null int64
16    101 non-null int64
17    101 non-null int64
dtypes: int64(17), object(1)
memory usage: 14.3+ KB
None
 <_io.TextIOWrapper name='datasets_selection' mode='r' encoding='cp1252'>

b'Skipping line 10: expected 34 fields, saw 35\n'
b'Skipping line 16: expected 19 fields, saw 20\nSkipping line 43: expected 19 fields, saw 20\nSkipping line 58: expected 19 fields, saw 20\nSkipping line 110: expected 19 fields, saw 20\nSkipping line 124: expected 19 fields, saw 20\nSkipping line 145: expected 19 fields, saw 20\nSkipping line 153: expected 19 fields, saw 20\nSkipping line 156: expected 19 fields, saw 20\nSkipping line 163: expected 19 fields, saw 20\nSkipping line 166: expected 19 fields, saw 20\nSkipping line 192: expected 19 fields, saw 20\nSkipping line 237: expected 19 fields, saw 20\nSkipping line 238: expected 19 fields, saw 20\nSkipping line 247: expected 19 fields, saw 20\nSkipping line 263: expected 19 fields, saw 20\nSkipping line 279: expected 19 fields, saw 20\nSkipping line 312: expected 19 fields, saw 20\nSkipping line 314: expected 19 fields, saw 20\nSkipping line 363: expected 19 fields, saw 20\nSkipping line 375: expected 19 fields, saw 20\nSkipping line 385: expected 19 fields, saw 20\nSkipping line 407: expected 19 fields, saw 21\nSkipping line 408: expected 19 fields, saw 21\nSkipping line 409: expected 19 fields, saw 21\nSkipping line 410: expected 19 fields, saw 21\nSkipping line 421: expected 19 fields, saw 21\nSkipping line 428: expected 19 fields, saw 20\nSkipping line 440: expected 19 fields, saw 20\nSkipping line 457: expected 19 fields, saw 20\nSkipping line 538: expected 19 fields, saw 20\nSkipping line 648: expected 19 fields, saw 20\nSkipping line 690: expected 19 fields, saw 20\nSkipping line 724: expected 19 fields, saw 20\nSkipping line 740: expected 19 fields, saw 20\nSkipping line 769: expected 19 fields, saw 20\nSkipping line 779: expected 19 fields, saw 20\nSkipping line 784: expected 19 fields, saw 20\nSkipping line 791: expected 19 fields, saw 20\nSkipping line 813: expected 19 fields, saw 20\nSkipping line 962: expected 19 fields, saw 20\nSkipping line 979: expected 19 fields, saw 20\nSkipping line 980: expected 19 fields, saw 20\nSkipping line 994: expected 19 fields, saw 20\nSkipping line 996: expected 19 fields, saw 20\nSkipping line 1006: expected 19 fields, saw 20\nSkipping line 1021: expected 19 fields, saw 20\nSkipping line 1027: expected 19 fields, saw 20\nSkipping line 1028: expected 19 fields, saw 20\nSkipping line 1064: expected 19 fields, saw 20\nSkipping line 1165: expected 19 fields, saw 20\nSkipping line 1172: expected 19 fields, saw 20\nSkipping line 1193: expected 19 fields, saw 20\nSkipping line 1197: expected 19 fields, saw 20\nSkipping line 1218: expected 19 fields, saw 20\nSkipping line 1231: expected 19 fields, saw 20\nSkipping line 1263: expected 19 fields, saw 20\nSkipping line 1296: expected 19 fields, saw 20\nSkipping line 1297: expected 19 fields, saw 20\nSkipping line 1303: expected 19 fields, saw 20\nSkipping line 1324: expected 19 fields, saw 20\nSkipping line 1334: expected 19 fields, saw 20\nSkipping line 1374: expected 19 fields, saw 20\nSkipping line 1405: expected 19 fields, saw 20\nSkipping line 1416: expected 19 fields, saw 20\nSkipping line 1459: expected 19 fields, saw 20\nSkipping line 1463: expected 19 fields, saw 20\n'